# action.yml
name: 'Veracode Declare Configure'
description: 'Use this action to Setup the Veracode estate required in the Declare configuration file'
inputs:
  configuration-file:
    description: 'Path to Declare configuration file'
    required: true
    default: 'veracode.json'
  ignore-schedule:
    description: 'Choose to ignore the schedule in the Decalre configuraiton file'
    required: true
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.configuration-file }}
    - ${{ inputs.ignore-schedule }}